export const CONTENTFUL_API_URL = process.env.NEXT_PUBLIC_CONTENTFUL_API_URL;

export const CONTENTFUL_SPACE = process.env.NEXT_PUBLIC_CONTENTFUL_SPACE;

export const CONTENTFUL_ACCESS_TOKEN =
  process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN;

export const CONTENTFUL_API_ENDPOINT = `${process.env.NEXT_PUBLIC_CONTENTFUL_API_URL}${process.env.CONTENTFUL_SPACE}`;
